### ISSUE TITLE
Deploy Infrastructure via Terraform

### ISSUE THREAD

**Issue by devalibvr** [plippe/aws-lambda-ip-availability#7]
Hi,

@plippe nice work! 
this is not an issue, just a question. Do you have any experience deploying this through Terraform? If so, I would appreciate it if you could provide me with the Terraform code if you have any. Besides that, does this code include sending an email notification when IPs are not available?

Ali

**Comment by plippe** [comment]
Hi @devalibvr,

My goodness, I haven't looked at this in a long time ...

Based on [package.json](https://github.com/plippe/aws-lambda-ip-availability/blob/master/package.json#L14-L16), I used cloud formation instead of Terraform
[cf2tf](https://github.com/DontShaveTheYak/cf2tf) should allow you to convert [the template](https://github.com/plippe/aws-lambda-ip-availability/blob/master/aws/resources.yml) to Terraform

Once you have it deployed, this will publish 2 data points to CloudWatch: `TotalIpAddress`, `AvailableIpAddress`
It will not create an alarm to notify you if the two metrics converge

I hope this information helps

**Comment by devalibvr** [comment]
@plippe Thanks. If you're interested in having resources in Terraform in case someone else needed in the future, I'd be happy create a PR later

**Comment by plippe** [comment]
@devalibvr thanks for the offer, but would prefer to not to update this repo
Feel free to fork it and create a Terraform version of it
